name: Build and push
on:
  push:
    branches:
      - release
      - feature/*

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "release"
          pre_release_branches: "development,feature/*"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build and push wpayz-backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: registry.digitalocean.com/kob-payment/wpayz-backend:${{ steps.tag_version.outputs.new_tag }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
      - name: Push Helm chart
        uses: bsord/helm-push@v4
        with:
          registry-url: https://museum-vjm6yelyza-as.a.run.app/
          username: megane
          password: 147973
          chart-folder: chart
          force: true
          version: ${{ steps.tag_version.outputs.new_tag }}
          appVersion: ${{ steps.tag_version.outputs.new_tag }}
